apiVersion: v1
kind: Service
metadata:
  name: {{ include "uni_chart.fullname" . }}
  labels:
    {{- include "uni_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port_web }}
      name: HTTP_port
      targetPort: http
      protocol: TCP
    - port: {{ .Values.service.port_api }}
      name: api_port
      targetPort: 11434
      protocol: TCP
      
  selector:
    {{- include "uni_chart.selectorLabels" . | nindent 4 }}
